### ISSUE TITLE
Unreliable FK detection resulting in "Object is not a DataObject" exception

### ISSUE THREAD

**Issue by andrus** [nhl/link-move#178]
Had a weird case where an FK column was pointing to multiple tables, one - that is indeed a master table for that FK, and a couple more with compound keys. This resulted in exception like the one below. The reason was that `TargetMerger` didn't recognize an FK as such (because an incorrect relationship was picked by `DefaultTargetEntity` at random from the 3 possibilities). This needs to be made more reliable somehow...

```

org.apache.cayenne.reflect.PropertyException: [v.4.1.RC2 Oct 25 2019 07:58:09] Error setting to-one DataObject property: player
at org.apache.cayenne.reflect.generic.DataObjectToOneProperty.setTarget(DataObjectToOneProperty.java:91)
at com.nhl.link.move.writer.TargetToOnePropertyWriter.write(TargetToOnePropertyWriter.java:20)
at com.nhl.link.move.runtime.task.createorupdate.TargetMerger.merge(TargetMerger.java:71)
at com.nhl.link.move.runtime.task.createorupdate.TargetMerger.lambda$merge$1(TargetMerger.java:52)
at com.nhl.dflib.map.Mapper.lambda$mapData$0(Mapper.java:20)
at java.lang.Iterable.forEach(Iterable.java:75)
at com.nhl.dflib.map.Mapper.mapData(Mapper.java:19)
at com.nhl.dflib.map.Mapper.map(Mapper.java:12)
at com.nhl.dflib.ColumnDataFrame.map(ColumnDataFrame.java:216)
at com.nhl.link.move.runtime.task.createorupdate.TargetMerger.merge(TargetMerger.java:52)
at com.nhl.link.move.runtime.task.createorupdate.CreateOrUpdateSegmentProcessor.mergeToTarget(CreateOrUpdateSegmentProcessor.java:81)
at com.nhl.link.move.runtime.task.createorupdate.CreateOrUpdateSegmentProcessor.process(CreateOrUpdateSegmentProcessor.java:56)
at com.nhl.link.move.runtime.task.createorupdate.CreateOrUpdateTask.lambda$createBatchProcessor$1(CreateOrUpdateTask.java:74)
at com.nhl.link.move.batch.BatchRunner.run(BatchRunner.java:51)
at com.nhl.link.move.runtime.task.createorupdate.CreateOrUpdateTask.run(CreateOrUpdateTask.java:64)

Caused by: org.apache.cayenne.reflect.PropertyException: [v.4.1.RC2 Oct 25 2019 07:58:09] Object is not a DataObject: 'java.lang.Integer'
at org.apache.cayenne.reflect.generic.DataObjectBaseProperty.toDataObject(DataObjectBaseProperty.java:101)
at org.apache.cayenne.reflect.generic.DataObjectToOneProperty.setTarget(DataObjectToOneProperty.java:86)
... 29 common frames omitted
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to org.apache.cayenne.DataObject
at org.apache.cayenne.reflect.generic.DataObjectBaseProperty.toDataObject(DataObjectBaseProperty.java:97)
```

**Comment by andrus** [comment]
narrowly fixed the case described in the issue. There are still too many edge cases with syncing FKs.
