### ISSUE TITLE
Transient target path support

### ISSUE THREAD

**Issue by dkoyro** [nhl/link-move#59]
It's intentionally or not, but the previous versions of Link ETL supported transient target paths. 
It allowed to transfer any source value to such a transient target for resolving it on further ETL stages (a usual case was to remap this transient value with the real one, which was fetched from the target DB or so).

Now it fails with the error:
Can't resolve path component: <transient target path>
	at org.apache.cayenne.map.PathComponentIterator.invalidPathException(PathComponentIterator.java:145)
	at org.apache.cayenne.map.PathComponentIterator.next(PathComponentIterator.java:133)
	at org.apache.cayenne.map.ObjEntity$DBPathConverter.toDbPath(ObjEntity.java:1141)
	at org.apache.cayenne.map.ObjEntity$DBPathConverter.transform(ObjEntity.java:1185)
	at org.apache.cayenne.exp.Expression.transformExpression(Expression.java:647)
	at org.apache.cayenne.exp.Expression.transform(Expression.java:598)
	at org.apache.cayenne.map.ObjEntity.translateToDbPath(ObjEntity.java:1077)
	at com.nhl.link.move.runtime.path.PathNormalizer$1.doNormalize(PathNormalizer.java:74)
	at com.nhl.link.move.runtime.path.PathNormalizer$1.normalize(PathNormalizer.java:64)
	at com.nhl.link.move.runtime.task.createorupdate.RowConverter.convert(RowConverter.java:43)
	at com.nhl.link.move.runtime.task.createorupdate.RowConverter.convert(RowConverter.java:31)
	at com.nhl.link.move.runtime.task.createorupdate.CreateOrUpdateSegmentProcessor.convertSrc(CreateOrUpdateSegmentProcessor.java:64)
	at com.nhl.link.move.runtime.task.createorupdate.CreateOrUpdateSegmentProcessor.process(CreateOrUpdateSegmentProcessor.java:56)
	at com.nhl.link.move.runtime.task.createorupdate.CreateOrUpdateTask$1.process(CreateOrUpdateTask.java:74)

**Comment by andrus** [comment]
"transient" target path got me confused initially. Here we are dealing with *invalid* target path , not *transient* (transient would mean a property of a target object that is non-persistent). 

So I think this feature should be done differently on the long run, as we are breaking a 1.4 rule that attribute's "target" should be a valid path that is resolvable against a target object. So we need an alternative solution - e.g. keep such values it in untranslated sources, but prevent them from leaking into maps keyed by target path.
